'use strict';

const { spawn } = require('node:child_process');
const path = require('node:path');

function describe() {
    return {
        platform: process.platform,
        arch: process.arch,
        node: process.version
    };
}

// The URL is always generated by the launcher itself (loopback host + numeric
// port), never taken from user input, so no shell is needed to open it.
function openBrowser(url) {
    let command;
    let args;
    if (process.platform === 'darwin') {
        command = 'open';
        args = [url];
    } else if (process.platform === 'win32') {
        command = 'rundll32.exe';
        args = ['url.dll,FileProtocolHandler', url];
    } else {
        command = 'xdg-open';
        args = [url];
    }
    try {
        const child = spawn(command, args, { detached: true, stdio: 'ignore' });
        child.unref();
        return true;
    } catch {
        return false;
    }
}

// Windows: start the .exe directly.
// macOS: start the executable inside the .app bundle instead of `open`, so the
// launcher keeps the game PID and can wait for it to exit. Unity resolves its
// data path from the executable location, not the working directory.
function launchGame(game, extraArgs = []) {
    if (game.kind === 'exe') {
        return spawn(game.path, extraArgs, {
            cwd: path.dirname(game.path),
            stdio: 'ignore'
        });
    }
    return spawn(game.binary, extraArgs, {
        cwd: path.resolve(game.path, '..'),
        stdio: 'ignore'
    });
}

module.exports = { describe, openBrowser, launchGame };
